apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao-sistema
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8181
      protocol: TCP
      targetPort: 80
  selector:
    name: aplicacao-sistema-pod